# Generated by Django 6.0.5 on 2026-05-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategori Buku'},
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('harga', models.PositiveIntegerField()),
                ('stok', models.IntegerField(default=0)),
                ('sampul', models.ImageField(blank=True, null=True, upload_to='buku/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.kategori')),
            ],
            options={
                'verbose_name_plural': 'Daftar Buku',
            },
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
